Add deploy maven-file command to lftools
The 'deploy maven-file' command uses mvn deploy-file plugin
for deploying rpms/debs to a nexus hosted repository.

Testing the initial implemtation confirms that yum repo on nexus
triggers metadata generation for the uploaded packages.

Jira: releng-160
Change-Id: I0a3af408f70d7d2551a187ec3561b5e609e733d5
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>
Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

diff --git a/shell/deploy b/shell/deploy
--- a/shell/deploy
+++ b/shell/deploy
@@ -65,6 +65,11 @@ deploy() {
             deploy_archives "$@"
             exit 0
             ;;
+        maven-file )
+            echo "Deploying artifacts..."
+            deploy_maven_file "$@"
+            exit 0
+            ;;
         files )
             echo "Deploying files..."
             echo "ERROR: Unimplemented."
@@ -161,6 +166,167 @@ deploy_archives() {
     popd
     rm -rf "$tmpdir"
 }
+
+deploy_maven_file_usage () {
+    echo "Usage: $0 <nexus_url> <repo_id> <file>"
+    echo ""
+    echo "Options:"
+    echo "    -b /path/to/mvn"
+    echo "    -l /path/to/global-settings.xml"
+    echo "    -s /path/to/settings.xml"
+    echo "    -a <artifact_id>"
+    echo "    -c <classifier>"
+    echo "    -g <group_id>"
+    echo "    -v <version>"
+}
+
+deploy_maven_file () {
+    # Deploy a file to a Nexus maven2 repository.
+    #
+    # Usage: deploy_maven_file <nexus_url> <repo_id> <file>
+    #        (Refer to help for full listing by passing -h)
+    #
+    #
+    # As this script uses mvn to deploy. The server configuration should be
+    # configured in your local settings.xml. By default the script uses the
+    # mvn default "~/.m2/settings.xml" for the configuration but this can be
+    # overrided in the following order:
+    #
+    #     1. Passed through CLI option "-s" ("-l" for global-settings)
+    #     2. Environment variable "$SETTINGS_FILE" ("$GLOBAL_SETTINGS_FILE" for global-settings)
+    #     3. Maven default "~/.m2/settings.xml".
+    #
+
+    #                          <group_id>
+    #                          <file_name>
+    #                          <global_settings_file>
+    #                          <settings_file>
+    #
+    #   <nexus_url>: URL of Nexus server. Eg: https://nexus.opendaylight.org
+    #   <repo_id>:              Repository ID for the repository
+    #   <group_id>:             Group ID for the repository
+    #   <file_name>:            Name of the file to upload
+    #   <classifier>:           File classifier
+    #   <maven_bin>:            Path of maven binaries
+    #   <global_settings_file>: Path for $GLOBAL_SETTINGS_FILE (optional)
+    #   <settings_file>:        Path for $SETTINGS_FILE (optional)
+
+    # User input
+    local nexus_url="$1"
+    local repo_id="$2"
+    local file="$3"
+
+    # Variables
+    local mvn_bin="mvn"
+    declare -a optional_params
+
+    while getopts a:b:c:g:l:hm:s:v: o; do
+      case "$o" in
+        h)
+            deploy_maven_file_usage
+            exit 0
+            ;;
+
+        ################
+        # Maven Config #
+        ################
+        b)
+            mvn_bin="$OPTARG"
+            ;;
+        l)
+            optional_params+=" -gs \"$OPTARG\""
+            ;;
+        s)
+            optional_params+=" -s \"$OPTARG\""
+            ;;
+
+        ###################
+        # Maven Artitfact #
+        ###################
+        a)
+            optional_params+=(" -DartifactId=\"$OPTARG\"")
+            ;;
+        c)
+            optional_params+=(" -Dclassifier=\"$OPTARG\"")
+            ;;
+        g)
+            optional_params+=(" -DgroupId=\"$OPTARG\"")
+            ;;
+        v)
+            optional_params+=(" -Dversion=\"$OPTARG\"")
+            ;;
+
+        [?])
+            deploy_maven_file_usage
+            exit 1
+            ;;
+      esac
+    done
+    shift $(($OPTIND-1))
+
+    set -x
+    eval echo "$mvn_bin"
+    eval echo ${optional_params[*]}
+    set +x
+
+    if [ -z "$3" ]; then
+        echo "Missing required arguments."
+        exit 1
+    fi
+
+    exit 0
+
+    ################
+    # Start script #
+    ################
+
+    local mvn_goals=("org.apache.maven.plugins:maven-deploy-plugin:deploy-file")
+
+    declare -a params
+
+    params+=("-DrepositoryId=\"$repo_id\"")
+    params+=("-Durl=\"$nexus_url\"")
+    params+=("-Dfile=\"$file\"")
+    params+=("-Dtype=\"$file_type\"")
+
+    local file_type="${file_name##*.}"
+
+    case "$file_type" in
+        deb )
+            echo "Deploying deb to $nexus_url"
+            basefile=$(basename -s .deb "$file_name")
+            artifactId=$(echo "$basefile" | cut -f 1 -d '_')
+            version=$(echo "$basefile" | cut -f 2- -d '_')
+            classifier="$(file_type)"
+            ;;
+        rpm )
+            echo "Deploying rpm to $nexus_url"
+            if grep -qE '\.s(rc\.)?rpm' <<<"$file_name"
+            then
+                rpmrelease=$(rpm -qp --queryformat="%{release}.src" "$file_name")
+            else
+                rpmrelease=$(rpm -qp --queryformat="%{release}.%{arch}" "$file_name")
+            fi
+            artifactId=$(rpm -qp --queryformat="%{name}" "$file_name")
+            version=$(rpm -qp --queryformat="%{version}" "$file_name")
+            version+="-$rpmrelease"
+            classifier="$(file_type)"
+            ;;
+        * )
+            echo "Invalid file type: $file_type" 1>&2
+            exit 1
+            ;;
+    esac
+
+    eval "$maven_bin" "${mvn_goals[*]}" "${params[*]}" "${optional_params[*]}"
+
+    # make sure the script bombs if we fail an upload
+    if [ "$?" != '0' ]; then
+        echo "ERROR: There was an error with the upload"
+        exit 1
+    fi
+}
+
 
 deploy_logs() {
     # Deploy logs to a Nexus site repository named logs.
