Add deploy Maven repo command
Use curl to deploy a Maven repository to Nexus.

Change-Id: If46e5054a2234eab77e7bd07120d8d0f11dfd293
Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

diff --git a/shell/deploy b/shell/deploy
--- a/shell/deploy
+++ b/shell/deploy
@@ -75,6 +75,11 @@ deploy() {
             deploy_logs "$@"
             exit 0
             ;;
+        maven )
+            echo "Deploying Maven artifacts..."
+            deploy_maven "$@"
+            exit 0
+            ;;
         * )
             echo "Invalid command: $subcommand" 1>&2
             exit 1
@@ -217,6 +222,41 @@ deploy_logs() {
 
     popd
     rm -rf "$tmpdir"
+}
+
+deploy_maven() {
+    # Deploy Maven artifacts using curl instead of Maven
+    #
+    # The purpose of this is so that we can get around the problematic
+    # deploy-at-end configuration with upstream Maven.
+    # https://issues.apache.org/jira/browse/MDEPLOY-193
+
+    local nexus_repo_url="$1"
+    local maven_repo_path="$2"
+    local project_path="$3"
+
+    if [ -z "$3" ]; then
+        echo "Missing required arguments."
+        echo "Usage: deploy maven <nexus_repo_url> <maven_repo_path> <project_path>"
+        exit 1
+    fi
+
+    pushd "$maven_repo_path/$project_path"
+    file_list=$(find . -type f \
+                ! -name "maven-metadata*" \
+                ! -name _remote.repositories \
+                ! -name resolver-status.properties \
+                | cut -c 3-)
+    popd
+
+    SAVE_IFS=$IFS
+    IFS=$'\n'
+    file_list=($file_list)
+    IFS=$SAVE_IFS
+
+    for file in "${file_list[@]}"; do
+        echo curl --upload-file "$file" "$nexus_repo_url/$project_path/$file)"
+    done
 }
 
 # Only run the script if it is being called directly and not sourced.
