Add deploy artifactis command
The deploy artifact command uses mvn deploy
for deploying artifacts to a nexus repository

Jira: releng-160
Change-Id: I0a3af408f70d7d2551a187ec3561b5e609e733d5
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>

diff --git a/shell/deploy b/shell/deploy
--- a/shell/deploy
+++ b/shell/deploy
@@ -65,6 +65,11 @@ deploy() {
             deploy_archives "$@"
             exit 0
             ;;
+        artifacts )
+            echo "Deploying artifacts..."
+            deploy_artifacts "$@"
+            exit 0
+            ;;
         files )
             echo "Deploying files..."
             echo "ERROR: Unimplemented."
@@ -161,6 +166,89 @@ deploy_archives() {
     popd
     rm -rf "$tmpdir"
 }
+
+
+deploy_artifacts () {
+    # Deploy artifact to a Nexus site repository.
+    #
+    # To use this script the Nexus server must have a repository configured.
+    # The script requires ~/.m2/settings.xml for authentication or the
+    # $GLOBAL_SETTINGS_FILE and $SETTINGS_FILE passed from job.
+    #
+    # Usage: deploy_artifacts <nexus_url> <repo_id> <file_name>
+    #
+    #   <nexus_url>:  URL of Nexus server. Eg: https://nexus.opendaylight.org
+    #   <repo-id>:    Repository ID for the repository
+    #   <file_name>:  Name of the file to upload
+
+    set -x
+    # WORKSPACE="/tmp"
+    # [ "$MVN" ] || MVN="/usr/bin/mvn"
+    local nexus_url="$1"
+    local repoId="$2"
+    #local version="$4"
+    #local artifactId="$5"
+    local file_name="$3"
+    local file_type="${file_name##*.}"
+    local classifier="$file_type"
+
+    case "$file_type" in
+        rpm )
+            echo "Deploying rpm to $nexus_url"
+            if grep -qE '\.s(rc\.)?rpm' <<<"$file_name"
+            then
+                rpmrelease=$(rpm -qp --queryformat="%{release}.src" "$file_name")
+            else
+                rpmrelease=$(rpm -qp --queryformat="%{release}.%{arch}" "$file_name")
+            fi
+            artifactId=$(rpm -qp --queryformat="%{name}" "$file_name")
+            version=$(rpm -qp --queryformat="%{version}" "$file_name")
+            ;;
+        deb )
+            echo "Deploying deb to $nexus_url"
+            basefile=$(basename -s .deb "$file_name")
+            artifactId=$(echo "$basefile" | cut -f 1 -d '_')
+            version=$(echo "$basefile" | cut -f 2- -d '_')
+            ;;
+        * )
+            echo "Invalid file type: $file_type" 1>&2
+            exit 1
+            ;;
+    esac
+
+    if [ -z "$3" ]; then
+        echo "Missing required arguments."
+        exit 1
+    fi
+
+    if [ -n "$8" ]; then
+        d_classifier="-Dclassifier=$classifier"
+    fi
+
+    tmpdir=$(mktemp -d)
+    pushd "$tmpdir"
+
+    # Disable checks for doublequote to prevent glob / splitting
+    # shellcheck disable=SC2086
+    "$MVN" org.apache.maven.plugins:maven-deploy-plugin:deploy-file \
+        -Dfile="$push_file" -DrepositoryId="$repoId" \
+        -Durl="$url" -DgroupId="$GROUP_ID" \
+        -Dversion="$version" -DartifactId="$artifactId" \
+        -Dtype="$file_type" "$d_classifier"\
+        -gs "$GLOBAL_SETTINGS_FILE" -s "$SETTINGS_FILE"
+        #| tee "$WORKSPACE/deploy-artifacts.log"
+
+    # make sure the script bombs if we fail an upload
+    if [ "$?" != '0' ]; then
+        echo "ERROR: There was an error with the upload"
+        exit 1
+    fi
+
+    popd
+    rm -rf "$tmpdir"
+    set +x
+}
+
 
 deploy_logs() {
     # Deploy logs to a Nexus site repository named logs.
