Improve error detection for when SSL invalid
If SSL cert is invalid we don't even reach the Nexus server. So add code
to check that status is 201 before proceeding.

Change-Id: Ic5c8a0ce4177f73e6f753001ee8bbc5fdf02956c
Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

diff --git a/shell/deploy b/shell/deploy
--- a/shell/deploy
+++ b/shell/deploy
@@ -327,6 +327,9 @@ EOF
         msg=$(sed -n -e 's/.*<msg>\(.*\)<\/msg>.*/\1/p' <<< $resp)
         echo "ERROR: $msg"
         exit "$status"
+    elif [ "$status" != "201" ]; then
+        echo "ERROR: Failed with status code $status"
+        exit "$status"
     fi
 
     local staging_repo_id
