Improve debugging output for deploy nexus-zip cmd
Issue: RT-50048
Change-Id: I54014819d18c0090c45fd8378954dc9aa5e540f8
Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

diff --git a/shell/deploy b/shell/deploy
--- a/shell/deploy
+++ b/shell/deploy
@@ -685,9 +685,16 @@ deploy_nexus_zip() {
         exit 1
     fi
 
-    echo "Pushing $deploy_zip to $nexus_repo on $nexus_url"
-    curl --netrc --upload-file "$deploy_zip" \
-        "${nexus_url}/service/local/repositories/${nexus_repo}/content-compressed/${nexus_path}"
+    echo "Pushing $deploy_zip to $nexus_repo on $nexus_url to path $nexus_path"
+    resp=$(curl -s -w "\\n\\n%{http_code}" --netrc --upload-file "$deploy_zip" \
+        "${nexus_url}/service/local/repositories/${nexus_repo}/content-compressed/${nexus_path}")
+    status=$(echo "$resp" | awk 'END {print $NF}')
+
+    if [ "$status" != 200 ]; then
+        echo "Failed with: $resp"
+        echo "Zip contains: $(unzip -l "$deploy_zip")"
+        exit "$status"
+    fi
 }
 
 upload_to_nexus() {
