Add deploy maven-file command to lftools
The 'deploy maven-file' command uses mvn deploy-file plugin
for deploying rpms/debs to a nexus hosted repository.

Testing the initial implemtation confirms that yum repo on nexus
triggers metadata generation for the uploaded packages.

Jira: releng-160
Change-Id: I0a3af408f70d7d2551a187ec3561b5e609e733d5
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>

diff --git a/shell/deploy b/shell/deploy
--- a/shell/deploy
+++ b/shell/deploy
@@ -65,6 +65,11 @@ deploy() {
             deploy_archives "$@"
             exit 0
             ;;
+        maven-file )
+            echo "Deploying artifacts..."
+            deploy_maven_file "$@"
+            exit 0
+            ;;
         files )
             echo "Deploying files..."
             echo "ERROR: Unimplemented."
@@ -161,6 +166,77 @@ deploy_archives() {
     popd
     rm -rf "$tmpdir"
 }
+
+
+deploy_maven_file () {
+    # Deploy maven-file to a Nexus maven2 repository.
+    #
+    # To use this script the Nexus server must have a maven2 repository configured
+    # with capabilities. The script requires passing "~/.m2/settings.xml" file,
+    # passed either through command line options or through environment variables
+    # $GLOBAL_SETTINGS_FILE and $SETTINGS_FILE from the JJB configration.
+    #
+    # Usage: deploy_maven_file <nexus_url> <repo_id> <file_name> <global_settings_file> <settings_file>
+    #
+    #   <nexus_url>: URL of Nexus server. Eg: https://nexus.opendaylight.org
+    #   <repo-id>: Repository ID for the repository
+    #   <file_name>: Name of the file to upload
+    #   <global_settings_file>: Path for $GLOBAL_SETTINGS_FILE
+    #   <settings_file>: Path for $SETTINGS_FILE
+
+    if [ -z "$3" ]; then
+        echo "Missing required arguments."
+        exit 1
+    fi
+
+    local nexus_url="$1"
+    local repoId="$2"
+    local file_name="$3"
+    local global_settings_file="${GLOBAL_SETTINGS_FILE:-$4}"
+    local settings_file="${SETTINGS_FILE:-$5}"
+    local file_type="${file_name##*.}"
+    local GROUP_ID="$repoId"
+    local d_classifier="-Dclassifier=$file_type"
+
+    case "$file_type" in
+        rpm )
+            echo "Deploying rpm to $nexus_url"
+            if grep -qE '\.s(rc\.)?rpm' <<<"$file_name"
+            then
+                rpmrelease=$(rpm -qp --queryformat="%{release}.src" "$file_name")
+            else
+                rpmrelease=$(rpm -qp --queryformat="%{release}.%{arch}" "$file_name")
+            fi
+            artifactId=$(rpm -qp --queryformat="%{name}" "$file_name")
+            version=$(rpm -qp --queryformat="%{version}" "$file_name")
+            version+="-$rpmrelease"
+            ;;
+        deb )
+            echo "Deploying deb to $nexus_url"
+            basefile=$(basename -s .deb "$file_name")
+            artifactId=$(echo "$basefile" | cut -f 1 -d '_')
+            version=$(echo "$basefile" | cut -f 2- -d '_')
+            ;;
+        * )
+            echo "Invalid file type: $file_type" 1>&2
+            exit 1
+            ;;
+    esac
+
+    "$MVN" org.apache.maven.plugins:maven-deploy-plugin:deploy-file \
+        -Dfile="$file_name" -DrepositoryId="$repoId" \
+        -Durl="$nexus_url" -DgroupId="$GROUP_ID" \
+        -Dversion="$version" -DartifactId="$artifactId" \
+        -Dtype="$file_type" "$d_classifier"\
+        -gs "$global_settings_file" -s "$settings_file" | tee "$WORKSPACE/$artifactId-maven-deploy-artifacts.log"
+
+    # make sure the script bombs if we fail an upload
+    if [ "$?" != '0' ]; then
+        echo "ERROR: There was an error with the upload"
+        exit 1
+    fi
+}
+
 
 deploy_logs() {
     # Deploy logs to a Nexus site repository named logs.
