Add patch-odl-release as a subcommand of version
This patch makes patch-odl-release be less specific to the OpenDaylight
project in case other projects might want to use it in the future. It
also moves it into the version tool as a sub-command.

Refactor cli code around to make it easier to manage version
subcommands.

Change-Id: I100927195f61c33584219445a9dfac1e3e59ceab
Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

diff --git a/shell/version b/shell/version
--- a/shell/version
+++ b/shell/version
@@ -62,6 +62,12 @@ version() {
             version_release
             exit 0
             ;;
+        patch )
+            RELEASE_TAG=$1
+            PATCH_DIR=$2
+            PROJECT=${3:-"OpenDaylight"}
+            version_patch
+            ;;
         * )
             echo "Invalid command: $subcommand" 1>&2
             print_version_usage
@@ -101,6 +107,77 @@ version_release() {
     do
         find . -type f -name "$name" -exec perl -i -pe "s/SNAPSHOT/$RELEASE_TAG/g" {} +
     done
+}
+
+version_patch() {
+    # Patches a git repo using bundle files and creates a version bump commit
+    #
+    # This command is a macro to perform 3 actions:
+    #
+    #  1) Apply a git.bundle patch to the current repo
+    #  2) Create a git tag against the commit provided by the git.bundle
+    #  3) Version bumps by x.y.(z+1)-SNAPSHOT to prepare repo for next dev cycle
+    #
+    # The original purpose of patch is to:
+    #
+    #  1) Apply autorelease patches for a ODL Release
+    #  2) Create version bump commit for post-release dev cycle
+    #
+    # However we  try to ensure the code here is not specific to the OpenDaylight
+    # project in case it is useful for other projects that need to patch multiple
+    # repos in a quick way using git.bundle files.
+    #
+    # Expected variables:
+    #     RELEASE_TAG - The release tag of the release being performed
+    #     PATCH_DIR   - The directory path containing the git.bundle files (and taglist.log)
+    #     PROJECT     - The top level project that we're patching eg. OpenDaylight
+
+    # OpenDaylight uses the format Boron-SR1 as a release tag where "boron" is
+    # the branch name of the maintenance branch and SR1 (if exists) is the
+    # service release. Strip out the branch from the tag and set the stable release
+    # branch.
+    STABLE_BRANCH="stable/$( cut -d '-' -f1 <<< "${RELEASE_TAG,,}")"
+
+
+    subproject="${PWD##*/}"
+
+    # Validate that we're patching at the same commit level as when autorelease
+    # built the release. Basically ensuring that no new patches snuck into the
+    # project during code freeze.
+    EXPECTED_HASH=$(grep "^${subproject} " "$PATCH_DIR/taglist.log" | awk '{ print $2 }')
+    if [ "$EXPECTED_HASH" == "" ]; then
+        parent_dir="$(dirname "$(pwd)")"
+        subproject="${parent_dir##*/}/$subproject"
+        EXPECTED_HASH=$(grep "^${subproject} " "$PATCH_DIR/taglist.log" | awk '{ print $2 }')
+    fi
+
+    git checkout "$EXPECTED_HASH"
+    CURRENT_HASH=$(git rev-parse HEAD)
+
+    echo "Current Hash: $CURRENT_HASH"
+    echo "Expected Hash: $EXPECTED_HASH"
+    if [ "$CURRENT_HASH" != "$EXPECTED_HASH" ]
+    then
+        echo "ERROR: Current project hash does not match expected hash"
+        exit 1
+    fi
+
+    #######################
+    # Start apply patches #
+    #######################
+    git fetch "${PATCH_DIR}/${subproject/\//-}.bundle"
+    git merge FETCH_HEAD
+    git tag -asm "$PROJECT $RELEASE_TAG release" "release/${RELEASE_TAG,,}"
+    find . -name pom.xml -print0 | xargs -0 grep SNAPSHOT
+
+    git checkout "${STABLE_BRANCH}"
+    # Release and then Bump so that the version.sh script creates the right patches
+    version_release "$RELEASE_TAG"
+    version_bump "$RELEASE_TAG"
+    git commit -asm "Bumping versions by x.y.(z+1) for next dev cycle"
+    find . -name pom.xml -print0 | xargs -0 grep "$RELEASE_TAG"
+
+    echo "Tagging and version bumping complete"
 }
 
 # Only run the script if it is being called directly and not sourced.
